project:
  type: website

website:
  title: "ADA Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Schedule.qmd
      - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

