project:
  type: website

website:
  title: "ADA Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Schedule.qmd
      - resources.qmd
      - href: datasets.qmd
        text: Datasets
      - href: workshop_kit.qmd
        text: Workshop Kit
        

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

