project:
  type: website

website:
  title: "ADA Workshop"
  twitter-card: true
  reader-mode: true
  google-analytics: "G-EB6VH8314S"
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Schedule.qmd
        text: Schedule
      - href: participants.qmd
        text: Participants
      - href: resources.qmd
        text: Resources
      - href: datasets.qmd
        text: Datasets
      - href: workshop_kit.qmd
        text: Workshop Kit
        

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

