---
title: "Datasets"
editor: visual
---

## Datasheets for Practice

1.  [Preparing data for importing in anthro](https://github.com/drpakhare/Workshop-NDA/blob/master/datasets_practice/dataset_preparation.xlsx) : This dataset has minimal variables and consist anthropometric data recorded by a surveyor as well as data of growth monitoring as recorded by AWW in her register. Participants will learn how to import data and map variables with this dataset.
2.  [Practice Dataset-2](https://github.com/drpakhare/Workshop-NDA/blob/master/datasets_practice/dataset_practice_2.csv): This dataset has other variables like Location of Residence, Wealth Index, State etc. Participants will learn to obtain prevalence estimates among subgroups of these variables.
3.  [Practice dataset of adolescent anthropometry](https://github.com/drpakhare/Workshop-NDA/blob/master/datasets_practice/3_dataset_practice_anthro_plus.csv): This dataset consist of anthropometry data of adolescents (10-19) years. Participants will learn how to use Anthro-Plus and other tools to compute various indicators.
4.  [Data quality assessment](https://github.com/drpakhare/Workshop-NDA/blob/master/datasets_practice/dataset_quality.xlsx): This dataset comprises anthropometry readings in children below 5 years. It will be used to demonstrate data quality assessment by using Anthro Survey Analyzer.
