---
title: "Schedule"
editor: visual
---

**Workshop Schedule**

+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| Time        | Session                                                                                 | Session Type      | Speaker/ Key Facilitator                                                           |
+=============+=========================================================================================+===================+====================================================================================+
| 9:30-10:00  | Introduction to workshop                                                                |                   | **Prof(Dr) Arun M Kokane,** Prof & Head, Community & Family Medicine, AIIMS Bhopal |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 10:00-10:30 | Formal Inauguration                                                                     |                   | **Prof(Dr) Ajai Singh,** Executive Director, AIIMS Bhopal                          |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 10:45-11:30 | Scientific basis of anthropometric measurements & indicators to monitor physical growth | Lecture           | **Dr Ankur Joshi,** Faculty, Community & Family Medicine, AIIMS Bhopal             |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 11:45-12:30 | Introduction to Anthro Survey Analyser                                                  | Lecture           | **Dr Sudhir Verma,** Senior Resident, Community & Family Medicine, AIIMS Bhopal    |
|             |                                                                                         |                   |                                                                                    |
|             | Preparing and importing anthropometric data                                             | Hands-on-practice |                                                                                    |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 12:45-13:30 | Computing Anthropometric Indicators                                                     | Hands-on-practice | **Dr Revadi G,** Senior Resident, Community & Family Medicine, AIIMS Bhopal        |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 15:00-15:30 | Understanding results                                                                   | Lecture           | **Dr Abhijit Pakhare,** Faculty, Community & Family Medicine, AIIMS Bhopal         |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 15:30-16:00 | Anthropometric Data Quality Assessment                                                  | Hands-on-practice | **Dr Ankur Joshi,** Faculty, Community & Family Medicine, AIIMS Bhopal             |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 16:10-16:40 | Generating summary report, exporting z-scores data                                      | Hands-on-practice | **Dr Abhijit Pakhare,** Faculty, Community & Family Medicine, AIIMS Bhopal         |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
| 16:45-17:15 | Valedictory Session and Certificate Distribution                                        |                   | **Organizing Team**                                                                |
+-------------+-----------------------------------------------------------------------------------------+-------------------+------------------------------------------------------------------------------------+
